// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyByR76PIDDccz6Dosf1P3BIuAZa2RN5quo',
//     appId: '1:553414402199:web:ad2972d46cfa376385c9d2',
//     messagingSenderId: '553414402199',
//     projectId: 'breed-plus',
//     authDomain: 'breed-plus.firebaseapp.com',
//     storageBucket: 'breed-plus.firebasestorage.app',
//     measurementId: 'G-68JG9LDZ3C',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCapS4bZyewzOoN0UraeVq61TuYxggRAH4',
//     appId: '1:553414402199:android:fb5dd992e8d4b05385c9d2',
//     messagingSenderId: '553414402199',
//     projectId: 'breed-plus',
//     storageBucket: 'breed-plus.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDtBsxFWfCRX3NhCxp0rf1KXV33T90K0wc',
//     appId: '1:553414402199:ios:cbf0e750d34466df85c9d2',
//     messagingSenderId: '553414402199',
//     projectId: 'breed-plus',
//     storageBucket: 'breed-plus.firebasestorage.app',
//     iosBundleId: 'com.example.uralBreed',
//   );
// }
